name: Publish pytest-hoverfly to PypI

on:
  workflow_dispatch:

jobs:
  publish-to-pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Install poetry
        run: make install_poetry
      - name: Install
        run: make prepare
      - name: Publish package to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: |
          . .venv/bin/activate
          poetry publish --build
